name: vit-covid19-xray
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - cudatoolkit=11.1
  - numpy>=1.21.0
  - pandas>=1.3.0
  - pillow>=8.3.0
  - opencv>=4.5.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - pip
  - pip:
    - timm>=0.4.0
    - torchmetrics>=0.5.0
    - tensorboard>=2.7.0
    - wandb>=0.12.0
    - tqdm>=4.62.0
    - pyyaml>=5.4.0
    - omegaconf>=2.1.0
    - onnx>=1.10.0
    - onnxruntime>=1.9.0
    - fastapi>=0.70.0
    - uvicorn>=0.15.0
